
GET http://localhost:5000/product/searchproducts
Content-Type: application/json

{
    "searchTerm": "Om"
}

###
GET http://localhost:5000/medicine/getsearchresults
Content-Type: application/json

{
    "searchTerm": "Bio "
}

# POST http://localhost:5000/product

###
POST https://medical-app-5gdu.onrender.com/product
Content-Type: application/json

{ 
  "title": "trailMedicine112", 
  "company": "Torrento Pharmaceuticals", 
  "quantity":"10pc", 
  "price": 19.39, 
  "discountedPrice": 20,
  "description": "In the PRINCE2 project management method" ,
  "category": "homeopathic",
  "availabilityStatus": "yes"
}

###
PUT http://localhost:5000/product/updateproduct/Deploy123
Content-Type: application/json

{
    "title":"Deploy123",
    "company": "Torrento Pharmaceuticals updated updated", 
    "quantity":"10pc", 
    "price": 19.39, 
    "discountedPrice": 20,
    "description": "In the PRINCE2 project management method" ,
    "category": "homeopathic",
    "availabilityStatus": "yes"
}

###
GET http://localhost:5000/product/downloadimages/Deploy123

###
# GET https://medical-app-5gdu.onrender.com/product/allproducts

###
# GET http://192.168.1.101:5000/product/allproducts

###
# GET http://localhost:5000/product/allproducts

###
# GET http://localhost:5000/product/getproducts
# Content-Type: application/json

# {
#     "page": 2,
#     "pageSize": 10
# }

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "gauri@gmail.com",
    "password" : "123"
}

###
GET http://192.168.1.3:5000/login/getaddressesbyuser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjYyNmE3NGFhNWRlMDM1MmFhZmJiMjAxIiwidXNlcm5hbWUiOiJnYXVyaUBnbWFpbC5jb20iLCJpYXQiOjE3MTM5NjE5NjJ9.kFhoun7aetE_MMR-geht6GBP881LNqvzHDLjRJ2Bd08

###
POST http://localhost:5000/login/addnewaddress
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjYyNmE3NGFhNWRlMDM1MmFhZmJiMjAxIiwidXNlcm5hbWUiOiJnYXVyaUBnbWFpbC5jb20iLCJpYXQiOjE3MTM5NjE5NjJ9.kFhoun7aetE_MMR-geht6GBP881LNqvzHDLjRJ2Bd08

{
    "newAddress" : "New Address...2"
}

###
DELETE http://localhost:5000/login/removeAddress
Content-Type: application/json

{
    "username": "Gauri",
    "index": 1
}

###
POST http://192.168.1.3:5000/login/validate
Content-Type: application/json

{
    "username": "gauri@gmail.com",
    "password" : "1234"
}

###
GET http://192.168.1.3:5000/login/authtest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjYyNmE3NGFhNWRlMDM1MmFhZmJiMjAxIiwidXNlcm5hbWUiOiJnYXVyaUBnbWFpbC5jb20iLCJpYXQiOjE3MTM5NjE5NjJ9.kFhoun7aetE_MMR-geht6GBP881LNqvzHDLjRJ2Bd08

###
GET http://192.168.1.3:5000/login/getcurrentuser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjYyNmE3NGFhNWRlMDM1MmFhZmJiMjAxIiwidXNlcm5hbWUiOiJnYXVyaUBnbWFpbC5jb20iLCJpYXQiOjE3MTM5NjE5NjJ9.kFhoun7aetE_MMR-geht6GBP881LNqvzHDLjRJ2Bd08

###
POST http://192.168.1.104:5000/product/uploadimages
Content-Type: application/json

{
    "data":"singleFile",
    "filename": "filename", 
    "productTitle":"dummy 1"
}

###
GET http://localhost:5000/medicine/addallmedicines

###
GET http://192.168.1.3:5000/medicine/getmedicinenames
Content-Type: application/json

{
    "category": "Biochemics"
}

###
GET http://192.168.1.3:5000/medicine/getmedicinedetails
Content-Type: application/json

{
    "title": "Silicea 6X",
    "company": "Schwabe"
}

###
POST http://192.168.1.103:5000/order/postorder
Content-Type: application/json

{
    "user_id": "65dd8ffc3f33f89b5111f936",
    "order_items": [
        {"title": "Calcarea phosphorica 6x",
        "company": "SBL",
        "package": "Tablets",
        "size": "6x 25g",
        "MRP": 105,
        "discountedPercentage": 10,
        "quantity": 2
        },
        {"title": "Calcarea Flurocia 3x",
        "company": "Schwabe",
        "package": "Tablets",
        "size": "6x 50g",
        "MRP": 105,
        "discountedPercentage": 10,
        "quantity": 3
        }
    ],
    "order_status": "PENDING",
    "shipping_address": "Sky home PG",
    "order_total": 210,
    "order_instruction": "keep it outside the door",
    "delivery_date": "2024-03-24",
    "order_timestamp": "2024-03-17"
}

###
GET http://192.168.1.3:5000/order/orderhistory

###
GET https://gauri-try.df.r.appspot.com/order/orderhistory

###
GET https://gauri-try.df.r.appspot.com/medicine/getmedicinedetails
Content-Type: application/json

{
    "title": "Silicea 6X",
    "company": "Schwabe"
}

###
GET https://gauri-try.df.r.appspot.com/medicine/getmedicinenames

###
POST https://gauri-try.df.r.appspot.com/order/postorder
Content-Type: application/json

{
    "user_id": "65dd8ffc3f33f89b5111f936",
    "order_items": [
        {"title": "Calcarea phosphorica 6x google test",
        "company": "SBL",
        "package": "Tablets",
        "size": "6x 25g",
        "MRP": 105,
        "discountedPercentage": 10,
        "quantity": 2
        },
        {"title": "Calcarea Flurocia 3x",
        "company": "Schwabe",
        "package": "Tablets",
        "size": "6x 50g",
        "MRP": 105,
        "discountedPercentage": 10,
        "quantity": 3
        }
    ],
    "order_status": "PENDING",
    "shipping_address": "Sky home PG",
    "order_total": 210,
    "order_instruction": "keep it outside the door",
    "delivery_date": "2024-03-24",
    "order_timestamp": "2024-03-17"
}
